### ISSUE TITLE
Bug: Long content gets cut off

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/bidss#64]
Take a look at the screenshot below. The content "Biomedical Informatics and Data Science Skills (BIDSS) Learning Platform" is cut off.

I can "work around" the issue by zooming out to 50% zoom, but this is less than ideal.

<img width="1056" alt="Screen Shot 2020-07-14 at 11 32 57" src="https://user-images.githubusercontent.com/5619885/87445356-7ccabc80-c5e7-11ea-8f5d-bca1fcca960e.png">

**Comment by aeisman** [comment]
I believe this has been resolved, if it recurs, please reopen.
